name: Test build release

on:
    pull_request:
        branches: ['*']
        types:
            - opened
            - synchronize
            - closed
    push:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    test-build-release:
        # commit the word "build" to the commit message to enable this job
        if: contains(github.event.head_commit.message, 'build')
        runs-on: ${{ matrix.os }}
        timeout-minutes: 30

        strategy:
            matrix:
                os: [macos-13, ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'npm'
            - run: npm ci
            - name: Install necessary FlatPak tools
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                  sudo apt update && sudo apt install flatpak flatpak-builder elfutils
            - name: Build release
              env:
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
                  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
                  APPLE_SIGNING_ID: ${{ secrets.APPLE_SIGNING_ID }}
              shell: bash
              run: |
                  npm ci
                  if [[ "${{ matrix.os }}" != "macos-13" ]]; then
                      npm run make
                  else
                      npm run make -- --arch=universal
                  fi
            - uses: actions/upload-artifact@v3
              with:
                  name: debug-build-${{ matrix.os }}
                  path: out/make
